name: wildfire
description: An conduit application with a database connection and data model.
version: 0.0.1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  conduit: ^2.0.0-0

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^2.0.0-0
