name: fs_test_agent
version: 2.0.0-b9
homepage: https://stablekernel.com
description: Utilities for writing tests to validate file system and Dart project directory operations.
environment: 
  sdk: '>=2.13.0-0 <3.0.0'
dependencies: 
  path: ^1.0.0
  pubspec: ^2.0.1
dev_dependencies: 
  lint: ^1.0.0
  test: ^1.16.4
