name: conduit_common
version: 2.0.0-b9
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  conduit_open_api: ^2.0.0-b9
  dcli: ^1.5.1
dev_dependencies: 
  lint: ^1.0.0
dependency_overrides: 
  conduit_codable: 
    path: ../codable
  conduit_open_api: 
    path: ../open_api
