name: conduit_isolate_exec
version: 2.0.0-b9
homepage: https://github.com/conduit-dart/isolate-exec
description: This library contains types that allow for executing code in a spawned isolate, perhaps with additional imports.
environment: 
  sdk: '>=2.13.0-0 <3.0.0'
dependencies: 
  analyzer: ^1.3.0
  glob: ^2.0.0
dev_dependencies: 
  dcli: ^1.5.1
  lint: ^1.5.3
  test: ^1.6.5
  test_package: 
    path: ../isolate_exec_test_package
